- TMessagesProj/src/main/java/org/telegram/ui/Cells/ChatMessageCell.java
- TMessagesProj/src/main/java/top/qwq2333/nullgram/config/ConfigManager.java
Distinguish anonymous admin and anonymous channel message
Show `Anonymous` title for anonymous admins when admin's title was blank
> feat: Distinguish anonymous admin and anonymous channel message

- TMessagesProj/src/main/java/org/telegram/ui/LaunchActivity.java
- TMessagesProj/src/main/java/org/telegram/ui/PhotoViewer.java
- TMessagesProj/src/main/java/top/qwq2333/nullgram/activity/ChatSettingActivity.java
- TMessagesProj/src/main/java/top/qwq2333/nullgram/utils/Defines.java
- TMessagesProj/src/main/res/values-zh/strings_nullgram.xml
- TMessagesProj/src/main/res/values/strings.xml
feat: Add disable volume keys to enable preview video sound
Add disable volume keys to enable preview video sound
> feat: Add disable volume keys to enable preview video sound

- build.gradle.kts
> Revert "build(deps): bump org.jetbrains.kotlin.android from Version.kotlin to 1.7.10"

- .github/ISSUE_TEMPLATE/bug_report.yml
Signed-off-by: wuhang2003 <108316419+wuhang2003@users.noreply.github.com>
**May require editing**
> fix: issues template

- TMessagesProj/src/main/java/org/telegram/ui/Components/FilterTabsView.java
- TMessagesProj/src/main/java/org/telegram/ui/DialogsActivity.java
- TMessagesProj/src/main/java/top/qwq2333/nullgram/activity/GeneralSettingActivity.java
- TMessagesProj/src/main/java/top/qwq2333/nullgram/utils/Defines.java
- TMessagesProj/src/main/res/values/strings_nullgram.xml
Hide All Chats Tab
feature #77
> feat: hide all chats tab

- TMessagesProj/src/main/java/org/telegram/ui/ChatActivity.java
- TMessagesProj/src/main/java/top/qwq2333/nullgram/activity/ChatSettingActivity.java
- TMessagesProj/src/main/java/top/qwq2333/nullgram/utils/Defines.java
Double tap translate
Add translate message action in custom double tap
> feat: double tap translate

- TMessagesProj/src/main/java/org/telegram/ui/ChatActivity.java
- TMessagesProj/src/main/java/top/qwq2333/nullgram/activity/ChatSettingActivity.java
fix: double tap translate
fix action bar position wrong
fix invalid hasDoubleTap
> fix: double tap translate

- TMessagesProj/src/main/java/top/qwq2333/nullgram/helpers/TranslateHelper.kt
- TMessagesProj/src/main/java/top/qwq2333/nullgram/utils/Log.kt
fix some glitches
fix: touch views in IO thread
> fix some glitches

- TMessagesProj/src/main/java/top/qwq2333/nullgram/utils/MessageUtils.java
fix: unable to save video sticker
now unable to save webm video sticker
> fix: unable to save video sticker

- TMessagesProj/src/main/java/org/telegram/messenger/MessageObject.java
fix: NPE when translate in photoviewer
NPE when translate in photoviewer
> fix: NPE when translate in photoviewer

- TMessagesProj/src/main/java/top/qwq2333/nullgram/activity/GeneralSettingActivity.java
- TMessagesProj/src/main/java/top/qwq2333/nullgram/helpers/TranslateHelper.kt
- TMessagesProj/src/main/java/top/qwq2333/nullgram/translate/BaseTranslator.kt
- TMessagesProj/src/main/java/top/qwq2333/nullgram/translate/providers/DeepLTranslator.kt
- TMessagesProj/src/main/java/top/qwq2333/nullgram/translate/providers/YandexTranslator.kt
- TMessagesProj/src/main/java/top/qwq2333/nullgram/utils/Defines.java
- TMessagesProj/src/main/res/values/strings_nullgram.xml
- buildSrc/src/main/kotlin/Version.kt
improved translation
add deepL translator
add yandex translator
> feat: improved translation

- TMessagesProj/src/main/java/org/telegram/messenger/LocaleController.java
fix: TELEOFFICIAL has not replace Telegram
> fix: tweak

- TMessagesProj/src/main/java/org/telegram/messenger/SharedConfig.java
- buildSrc/src/main/kotlin/Version.kt
> fix: wrong serializedData for proxy list 

- TMessagesProj/src/main/java/org/telegram/messenger/SharedConfig.java
- buildSrc/src/main/kotlin/Version.kt
> Revert "fix: wrong serializedData for proxy list "

- TMessagesProj/src/main/java/org/telegram/messenger/SharedConfig.java
- buildSrc/src/main/kotlin/Version.kt
compatible with wrong serializedData for proxy list
> fix: proxy lists NegativeArraySizeException

- TMessagesProj/build.gradle.kts
- TMessagesProj/src/main/java/org/telegram/messenger/ApplicationLoader.java
- build.gradle.kts
- buildSrc/src/main/kotlin/Version.kt
- gradle.properties
- gradle/libs.versions.toml
- gradle/wrapper/gradle-wrapper.properties
migrate to version catalogs
update gradle
remove multiDex
> build: migrate to version catalogs

- TMessagesProj/src/main/java/org/telegram/ui/ChatActivity.java
- buildSrc/src/main/kotlin/Version.kt
Fix copying message content not working in ChatActivity action mode
None.
> fix: copy message content not working

- TMessagesProj/src/main/java/org/telegram/ui/Components/AlertsCreator.java
- TMessagesProj/src/main/java/org/telegram/ui/PhotoViewer.java
Fix inconsistent state of check box when delete msg
None
> fix: inconsistent state of check box

- TMessagesProj/src/main/java/top/qwq2333/nullgram/translate/providers/DeepLTranslator.kt
> fix: deepl translate error

- TMessagesProj/src/main/java/top/qwq2333/nullgram/helpers/TranslateHelper.kt
- TMessagesProj/src/main/java/top/qwq2333/nullgram/translate/providers/LingoTranslator.kt
- TMessagesProj/src/main/java/top/qwq2333/nullgram/translate/providers/TranSmartTranslator.kt
- TMessagesProj/src/main/res/values-zh-rTW/strings_nullgram.xml
- TMessagesProj/src/main/res/values-zh/strings_nullgram.xml
- TMessagesProj/src/main/res/values/strings_nullgram.xml
> feat: add TranSmartTranslator

- .github/workflows/ci.yml
> Revert "chore(deps): bump actions/download-artifact from 2 to 4.1.7 in /.github/workflows"
